### ISSUE TITLE
Repeat with undefined variable

### ISSUE THREAD

**Issue by lukasoppermann** [popeindustries/lit-html-server#120]
I get an error when I use the repeat directive with an empty / undefined variable. However this happens sometimes with templates when a certain value is undefined for some instances, but not for others. Is this supposed to not be handled by design?

Thank you for the clarification.
Cheers
Lukas

**Comment by popeindustries** [comment]
The `items` you send into the repeat directive needs to be an array, but the values can be `undefined`. This is the same behaviour as `lit-html` in the browser.

`undefined` values should otherwise work fine, but again, some directives may throw errors. Do you have a specific example of `undefined` causing errors (with stack trace) I could look at?

**Comment by lukasoppermann** [comment]
No, thanks, I actually had `undefined` without an array, I'll adjust the transformer to solve this, thanks.
