### ISSUE TITLE
Question on `unsafeHTML` with Buffers

### ISSUE THREAD

**Issue by jordanthornquest** [popeindustries/lit-html-server#133]
Quick question: I'm using this library with a static-site generator. The generator in question accepts Strings or Buffers as return values, which it will render to HTML. I usually nest pages within layouts. Both the pages and the layouts in question are rendered with this library.

If I render all of my `lit-html-server` templates as Buffers, I'm able to render pages-nested-in-layouts successfully, without using the `unsafeHTML` directive. If I render the templates as Strings, I have to use `unsafeHTML` to make sure that pages-nested-in-layouts escape and render as expected.

I can even use `renderToString` within a top-level layout without using `unsafeHTML` if the template passed inside of that layout is a Buffer.

An example:

```javascript
// page.js 
const page = html`<h1>Hello world</h1>`

const rendered = await renderToBuffer(page);
return rendered;

// layout.js
const layoutBuilder = async function(content) {
  const template = html`
    <html>
      <body>
        ${content}
      </body>
    </html>
  `
  return template;
}

const layout = await layoutBuilder(page);
const rendered = await renderToString(layout);
return rendered;
```

Is this expected behavior with this library, or is it supposed to be a requirement to use `unsafeHTML` to render both Strings and Buffers?

**Comment by popeindustries** [comment]
Quick answer: `unsafeHTML` shouldn't be necessary here. 

It is true that, if you are rendering a string expression that contains tags, you need to skip escaping via `unsafeHTML`, so that part is working as expected. I think what you want to do is pass the `TemplateResult` from `page` directly to your `layoutBuilder` function. That is, you don't need to `renderToBuffer` more than once, just nest the templates.

**Comment by jordanthornquest** [comment]
Good to know. Thanks a bunch.
